Imorest/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Imorest.Models
{
    public class Alert
    {
        
        public int alertID { get; set; }
        
        public int clientId { get; set; }
        public virtual Client Client { get; set; }

        [RegularExpression("^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Invalid designation")]
        [Required]
        [StringLength(100)]
        public string alertRef  { get; set; }

        public ICollection<Parameter> Parameters { get; set; }

    }
}

Imorest/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Imorest.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace Imorest.Controllers
{
    public class AlertsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Alerts
        public ActionResult Index()
        {

            try
            {
                var roleStore = new RoleStore<IdentityRole>(db);
                var roleManager = new RoleManager<IdentityRole>(roleStore);
                var userStore = new UserStore<ApplicationUser>(db);
                var userManager = new UserManager<ApplicationUser>(userStore);
                var role = roleManager.FindByName("Client");
                //
                if (role == null)
                {
                    // aqui sai em erro para pagina a criar
                    return Content("There are no Client Roles in the System!");
                }
                else
                {

                    var user = userManager.FindByName(User.Identity.Name);

                    if (user != null)
                    {
                        var rolesForUser = userManager.GetRoles(user.Id);
                        if (rolesForUser == null || !rolesForUser.Contains("Client"))
                        {
                            // aqui sai em erro
                            return Content("User has no Client access!");
                        }
                    }
                    else
                    {
                        return Content("User doesn't exist!");
                    }
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                var sb = new System.Text.StringBuilder();
                foreach (var failure in ex.EntityValidationErrors)
                {
                    sb.AppendFormat("{0} failed validation", failure.Entry.Entity.GetType());
                    foreach (var error in failure.ValidationErrors)
                    {
                        sb.AppendFormat("- {0} : {1}", error.PropertyName, error.ErrorMessage);
                        sb.AppendLine();
                    }
                }

                throw new Exception(sb.ToString());
            }

            var alerts = db.Alerts.Include(a => a.Client);
            return View(alerts.ToList());
        }

        // GET: Alerts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // GET: Alerts/Create
        public ActionResult Create()
        {
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name");
            return View();
        }

        // POST: Alerts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "alertID,clientId,alertRef")] Alert alert)
        {
            var userStore = new UserStore<ApplicationUser>(db);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var user = userManager.FindByName(User.Identity.Name);
            //var client = db.Clients.Where(a => a.userID == user.Id);
            var client = db.Clients.Single(c => c.userID == user.Id);
            if (ModelState.IsValid)
            {
                alert.clientId = client.clientId;
                db.Alerts.Add(alert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);


            return View(alert);
        }

        // GET: Alerts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);
            return View(alert);
        }

        // POST: Alerts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "alertID,clientId,alertRef")] Alert alert)
        {
            var userStore = new UserStore<ApplicationUser>(db);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var user = userManager.FindByName(User.Identity.Name);
            //var client = db.Clients.Where(a => a.userID == user.Id);
            var client = db.Clients.Single(c => c.userID == user.Id);
            if (ModelState.IsValid)
            {
                alert.clientId = client.clientId;
                db.Entry(alert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);
            return View(alert);
        }

        // GET: Alerts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // POST: Alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alert alert = db.Alerts.Find(id);
            db.Alerts.Remove(alert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Imorest/Controllers/ParametersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Imorest.Models;

namespace Imorest.Controllers
{
    public class ParametersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Parameters
        public ActionResult Index()
        {
            var parameters = db.Parameters.Include(p => p.Alert);
            return View(parameters.ToList());
        }

        // GET: Parameters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parameter parameter = db.Parameters.Find(id);
            if (parameter == null)
            {
                return HttpNotFound();
            }
            return View(parameter);
        }

        // GET: Parameters/Create
        public ActionResult Create()
        {
            ViewBag.AlertID = new SelectList(db.Alerts, "alertID", "alertRef");
            return View();
        }

        // POST: Parameters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "parameterID,name,price,area,AlertID")] Parameter parameter)
        {
            if (ModelState.IsValid)
            {
                db.Parameters.Add(parameter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AlertID = new SelectList(db.Alerts, "alertID", "alertRef", parameter.AlertID);
            return View(parameter);
        }

        // GET: Parameters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parameter parameter = db.Parameters.Find(id);
            if (parameter == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlertID = new SelectList(db.Alerts, "alertID", "alertRef", parameter.AlertID);
            return View(parameter);
        }

        // POST: Parameters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "parameterID,name,price,area,AlertID")] Parameter parameter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parameter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AlertID = new SelectList(db.Alerts, "alertID", "alertRef", parameter.AlertID);
            return View(parameter);
        }

        // GET: Parameters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parameter parameter = db.Parameters.Find(id);
            if (parameter == null)
            {
                return HttpNotFound();
            }
            return View(parameter);
        }

        // POST: Parameters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Parameter parameter = db.Parameters.Find(id);
            db.Parameters.Remove(parameter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Imorest/Views/Alerts/Create.cshtml
@model Imorest.Models.Alert

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.clientId, "clientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("clientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.clientId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.alertRef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alertRef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alertRef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div>
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Manage Parameters", "Index","Parameters")
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Imorest/Views/Alerts/Delete.cshtml
@model Imorest.Models.Alert

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alertRef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alertRef)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Imorest/Views/Alerts/Details.cshtml
@model Imorest.Models.Alert

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alertRef)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alertRef)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.alertID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Imorest/Views/Alerts/Edit.cshtml
@model Imorest.Models.Alert

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.alertID)

        @*<div class="form-group">
            @Html.LabelFor(model => model.clientId, "clientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("clientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.clientId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.alertRef, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alertRef, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alertRef, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("Manage Parameters", "Index", "Parameters")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Imorest/Views/Alerts/Index.cshtml
@model IEnumerable<Imorest.Models.Alert>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
           @* @Html.DisplayNameFor(model => model.Client.name)*@
            Name
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.alertRef)*@
            Alert Reference
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Client.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.alertRef)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.alertID }) |
            @Html.ActionLink("Details", "Details", new { id=item.alertID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.alertID })
        </td>
    </tr>
}

</table>