Imorest/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Imorest.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace Imorest.Controllers
{
    public class AlertsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Alerts
        public ActionResult Index()
        {

            try
            {
                var roleStore = new RoleStore<IdentityRole>(db);
                var roleManager = new RoleManager<IdentityRole>(roleStore);
                var userStore = new UserStore<ApplicationUser>(db);
                var userManager = new UserManager<ApplicationUser>(userStore);
                var role = roleManager.FindByName("Client");
                //
                if (role == null)
                {
                    // aqui sai em erro para pagina a criar
                    return Content("There are no Client Roles in the System!");
                }
                else
                {

                    var user = userManager.FindByName(User.Identity.Name);

                    if (user != null)
                    {
                        var rolesForUser = userManager.GetRoles(user.Id);
                        if (rolesForUser == null || !rolesForUser.Contains("Client"))
                        {
                            // aqui sai em erro
                            return Content("User has no Client access!");
                        }
                    }
                    else
                    {
                        return Content("User doesn't exist!");
                    }
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException ex)
            {
                var sb = new System.Text.StringBuilder();
                foreach (var failure in ex.EntityValidationErrors)
                {
                    sb.AppendFormat("{0} failed validation", failure.Entry.Entity.GetType());
                    foreach (var error in failure.ValidationErrors)
                    {
                        sb.AppendFormat("- {0} : {1}", error.PropertyName, error.ErrorMessage);
                        sb.AppendLine();
                    }
                }

                throw new Exception(sb.ToString());
            }

            var alerts = db.Alerts.Include(a => a.Client);
            return View(alerts.ToList());
        }

        // GET: Alerts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // GET: Alerts/Create
        public ActionResult Create()
        {
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name");
            return View();
        }

        // POST: Alerts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "alertID,clientId,alertRef")] Alert alert)
        {
            var userStore = new UserStore<ApplicationUser>(db);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var user = userManager.FindByName(User.Identity.Name);
            //var client = db.Clients.Where(a => a.userID == user.Id);
            var client = db.Clients.Single(c => c.userID == user.Id);
            if (ModelState.IsValid)
            {
                alert.clientId = client.clientId;
                db.Alerts.Add(alert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);


            return View(alert);
        }

        // GET: Alerts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);
            return View(alert);
        }

        // POST: Alerts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "alertID,clientId,alertRef")] Alert alert)
        {
            var userStore = new UserStore<ApplicationUser>(db);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var user = userManager.FindByName(User.Identity.Name);
            //var client = db.Clients.Where(a => a.userID == user.Id);
            var client = db.Clients.Single(c => c.userID == user.Id);
            if (ModelState.IsValid)
            {
                alert.clientId = client.clientId;
                db.Entry(alert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.clientId = new SelectList(db.Clients, "clientId", "name", alert.clientId);
            return View(alert);
        }

        // GET: Alerts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // POST: Alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alert alert = db.Alerts.Find(id);
            db.Alerts.Remove(alert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Imorest/Views/Shared/IndexAdmin.cshtml
@{
    ViewBag.Title = "Imorest Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="text-align: center">
    <p class="lead">Welcome to Imorest</p>
    
    <p><img src="~/Content/calgary-canada-real-estate-002.jpg" /></p>


</div>>

<div class="row">
    <div class="col-md-4">

        <p>Manage all your Adverts</p>

    </div>
    <div class="col-md-4">
        <p>Manage Real Estate Types</p>

    </div>
    <div class="col-md-4">
        <p>Manage your Alerts</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">

        <a href="@Url.Action("Index", "Advertisements")" class="btn btn-primary btn-large btn-block disabled" id="button1">
            <span class="glyphicon glyphicon-th-large"></span> Advertisements
        </a>

    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "RealEstateTypes")" class="btn btn-primary btn-large btn-block">
            <span class="glyphicon glyphicon-home"></span> RealEstateTypes
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "Alerts")" class="btn btn-primary btn-large btn-block disabled">
            <span class="glyphicon glyphicon-bell"></span> Alerts
        </a>
    </div>
</div>

Imorest/Views/Shared/IndexClient.cshtml
@{
    ViewBag.Title = "Imorest Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="text-align: center">
    <p class="lead">Welcome to Imorest</p>
    <p>Here you can manage all your advertisements and alerts</p>
    <p><img src="~/Content/calgary-canada-real-estate-002.jpg" /></p>
        
    
</div>

<div class="row">
    <div class="col-md-4">

        <p>Manage all your Adverts</p>

    </div>
    <div class="col-md-4">
        <p>Manage Real Estate Types</p>

    </div>
    <div class="col-md-4">
        <p>Manage your Alerts</p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">

        <a href="@Url.Action("Index", "Advertisements")" class="btn btn-primary btn-large btn-block " id="button1">
            <span class="glyphicon glyphicon-th-large"></span> Advertisements
        </a>

    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "RealEstateTypes")" class="btn btn-primary btn-large btn-block disabled">
            <span class="glyphicon glyphicon-home"></span> RealEstateTypes
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "Alerts")" class="btn btn-primary btn-large btn-block ">
            <span class="glyphicon glyphicon-bell"></span> Alerts
        </a>
    </div>
</div>

Imorest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  Iteration II</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/App.js"></script>
    <script src="~/Scripts/materialize.js"></script>

    <link href="~/Scripts/style.css" rel="stylesheet" />
    <script src="~/Scripts/angular-materialize.js"></script>

</head>
<body  class="row">
   

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("IMOREST", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

            </ul>
            @Html.Partial("_LoginPartial")
           
        </div>
    </div>
</div>
<div class="container body-content">
  
    @RenderBody()

    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Imorest Application Iteration II</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>